//
// Created by luogan on 16-10-14.
//

#ifndef DBPROJECT_CONSTS_H
#define DBPROJECT_CONSTS_H

#define TYPE_INT 0
#define TYPE_CHAR 1
#define TYPE_VARCHAR 2

#define INDEX_CLUSTERED 'a'
#define INDEX_UNCLUSTERED_UNIQUE 'b'
#define INDEX_UNCLUSTERED 'c'

#define COMPARE_EQUAL 0
#define COMPARE_NOT_EQUAL 1
#define COMPARE_LARGER 2
#define COMPARE_SMALLER 3
#define COMPARE_UNDEFINED 4

#endif //DBPROJECT_CONSTS_H
